spring:
  application:
      name: quiz
      security:
        jwt:
          secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
          expiration: 86400000 # a day
          refresh-token:
            expiration: 604800000 # 7 days
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
